server.port=8083
vlad.services.catalogue.uri=http://localhost:8081

spring.datasource.url=jdbc:postgresql://localhost:5434/customer_app
spring.datasource.username=customer_app
spring.datasource.password=customer_app

spring.flyway.schemas=public,customer_app

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8082/realms/RecipeManagementSystem
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.client-id=customer-app
spring.security.oauth2.client.registration.keycloak.client-secret=Plyv3Jyjbw0Fomg9O7OIRGOjgt2E9Bky
spring.security.oauth2.client.registration.keycloak.scope=openid,view_catalogue
